version: '3'
services:
  app:
    image: mail_pusher_api
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: local_nginx_server
    build:
      context: /Users/srinathkarthikeyan/nginx-conf
      dockerfile: Dockerfile
    ports:
      - 80:8000
    depends_on:
      - app
